### PR TITLE
Add cache to isConstant and isContainsHook

### PR DESCRIPTION
**Pull request by SukkaW**
Speed up things a little bit.

### CODE REVIEW

**Comment by lxsmnsyc** [comment]
Any scenarios this is useful?

**Comment by SukkaW** [comment]
@lxsmnsyc Should I rebase this PR to target the latest next branch, or should I close it? IMHO caching is constant check is still helpful.

**Comment by lxsmnsyc** [comment]
You can still keep it for the next branch. If you can resolve it, it can be included for 0.5.0

**Comment by SukkaW** [comment]
@lxsmnsyc I have rebased the PR to the latest `next` branch. And the cache hit ratio is impressive:

<details>
<summary>Screenshots</summary>
image
image
</details>

**Comment by lxsmnsyc** [comment]
Rather than a cache map (for mapping instances to their cache), I guess we can look into including it to the Optimizer instance? Might be faster than checking for the cache every time.

**Comment by SukkaW** [comment]
> Rather than a cache map (for mapping instances to their cache), I guess we can look into including it to the Optimizer instance? Might be faster than checking for the cache every time.

Agreed. Working on that now.

**Comment by lxsmnsyc** [comment]
Thank you

**Pull request merged**
